// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/image_ops.dart';
import 'api/imageproc_ops.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -865042172;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_lume',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Uint8List crateApiImageprocOpsAdaptiveThreshold({
    required List<int> imageBytes,
    required int blockRadius,
  });

  Uint8List crateApiImageOpsAdjustBrightness({
    required List<int> imageBytes,
    required int value,
  });

  Uint8List crateApiImageOpsAdjustContrast({
    required List<int> imageBytes,
    required double value,
  });

  Uint8List crateApiImageprocOpsBilateralFilter({
    required List<int> imageBytes,
    required int windowSize,
    required double sigmaColor,
    required double sigmaSpatial,
  });

  Uint8List crateApiImageOpsBlur({
    required List<int> imageBytes,
    required double sigma,
  });

  Uint8List crateApiImageprocOpsBoxFilter({
    required List<int> imageBytes,
    required int xRadius,
    required int yRadius,
  });

  Uint8List crateApiImageprocOpsCanny({
    required List<int> imageBytes,
    required double lowThreshold,
    required double highThreshold,
  });

  Uint8List crateApiImageOpsConvertFormat({
    required List<int> imageBytes,
    required String targetFormat,
  });

  Uint8List crateApiImageOpsCreateBlank({
    required int width,
    required int height,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageOpsCrop({
    required List<int> imageBytes,
    required int x,
    required int y,
    required int width,
    required int height,
  });

  Uint8List crateApiImageprocOpsDilate({
    required List<int> imageBytes,
    required int radius,
  });

  Uint8List crateApiImageprocOpsDistanceTransform({
    required List<int> imageBytes,
  });

  Uint8List crateApiImageprocOpsDrawAntialiasedLine({
    required List<int> imageBytes,
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawCross({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawCubicBezier({
    required List<int> imageBytes,
    required double startX,
    required double startY,
    required double endX,
    required double endY,
    required double ctrl1X,
    required double ctrl1Y,
    required double ctrl2X,
    required double ctrl2Y,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawFilledCircle({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int radius,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawFilledEllipse({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int widthRadius,
    required int heightRadius,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawFilledPolygon({
    required List<int> imageBytes,
    required List<LumePoint> points,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawFilledRect({
    required List<int> imageBytes,
    required int x,
    required int y,
    required int width,
    required int height,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawHollowCircle({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int radius,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawHollowEllipse({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int widthRadius,
    required int heightRadius,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawHollowPolygon({
    required List<int> imageBytes,
    required List<LumePoint> points,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawHollowRect({
    required List<int> imageBytes,
    required int x,
    required int y,
    required int width,
    required int height,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsDrawLine({
    required List<int> imageBytes,
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    required int r,
    required int g,
    required int b,
    required int a,
  });

  Uint8List crateApiImageprocOpsEqualizeHistogram({
    required List<int> imageBytes,
  });

  Uint8List crateApiImageprocOpsErode({
    required List<int> imageBytes,
    required int radius,
  });

  Uint8List crateApiImageOpsExtractChannel({
    required List<int> imageBytes,
    required int channel,
  });

  List<LumeContour> crateApiImageprocOpsFindContours({
    required List<int> imageBytes,
  });

  Uint8List crateApiImageOpsFlipHorizontal({required List<int> imageBytes});

  Uint8List crateApiImageOpsFlipVertical({required List<int> imageBytes});

  Uint8List crateApiImageprocOpsGaussianBlur({
    required List<int> imageBytes,
    required double sigma,
  });

  Uint8List crateApiImageprocOpsGaussianNoise({
    required List<int> imageBytes,
    required double mean,
    required double stddev,
    required BigInt seed,
  });

  LumeImageInfo crateApiImageOpsGetImageInfo({required List<int> imageBytes});

  LumeColor crateApiImageOpsGetPixel({
    required List<int> imageBytes,
    required int x,
    required int y,
  });

  Uint8List crateApiImageOpsGrayscale({required List<int> imageBytes});

  String crateApiSimpleGreet({required String name});

  Uint8List crateApiImageOpsHuerotate({
    required List<int> imageBytes,
    required int degrees,
  });

  Future<void> crateApiSimpleInitApp();

  Uint8List crateApiImageOpsInvertColors({required List<int> imageBytes});

  Uint8List crateApiImageprocOpsLaplacianFilter({
    required List<int> imageBytes,
  });

  Uint8List crateApiImageprocOpsMedianFilter({
    required List<int> imageBytes,
    required int xRadius,
    required int yRadius,
  });

  Uint8List crateApiImageprocOpsMorphologicalClose({
    required List<int> imageBytes,
    required int radius,
  });

  Uint8List crateApiImageprocOpsMorphologicalOpen({
    required List<int> imageBytes,
    required int radius,
  });

  Uint8List crateApiImageprocOpsOtsuThreshold({required List<int> imageBytes});

  Uint8List crateApiImageOpsOverlay({
    required List<int> baseBytes,
    required List<int> overlayBytes,
    required PlatformInt64 x,
    required PlatformInt64 y,
  });

  Uint8List crateApiImageOpsResize({
    required List<int> imageBytes,
    required int width,
    required int height,
    required bool keepAspectRatio,
  });

  Uint8List crateApiImageOpsResizeWithFilter({
    required List<int> imageBytes,
    required int width,
    required int height,
    required String filter,
  });

  Uint8List crateApiImageOpsRotate({
    required List<int> imageBytes,
    required int degrees,
  });

  Uint8List crateApiImageprocOpsRotateAboutCenter({
    required List<int> imageBytes,
    required double theta,
    required int bgR,
    required int bgG,
    required int bgB,
    required int bgA,
  });

  Uint8List crateApiImageprocOpsSaltAndPepperNoise({
    required List<int> imageBytes,
    required double rate,
    required BigInt seed,
  });

  Uint8List crateApiImageprocOpsSeamCarveWidth({
    required List<int> imageBytes,
    required int newWidth,
  });

  Uint8List crateApiImageOpsSharpen({
    required List<int> imageBytes,
    required double sigma,
    required int threshold,
  });

  Uint8List crateApiImageprocOpsSharpen3X3({required List<int> imageBytes});

  Uint8List crateApiImageprocOpsSharpenGaussian({
    required List<int> imageBytes,
    required double sigma,
    required double amount,
  });

  Uint8List crateApiImageprocOpsSobelGradients({required List<int> imageBytes});

  Uint8List crateApiImageprocOpsStretchContrast({
    required List<int> imageBytes,
    required int inputLower,
    required int inputUpper,
    required int outputLower,
    required int outputUpper,
  });

  Uint8List crateApiImageprocOpsThreshold({
    required List<int> imageBytes,
    required int value,
    required bool invert,
  });

  Uint8List crateApiImageOpsThumbnail({
    required List<int> imageBytes,
    required int maxWidth,
    required int maxHeight,
  });

  Uint8List crateApiImageOpsThumbnailExact({
    required List<int> imageBytes,
    required int width,
    required int height,
  });

  Uint8List crateApiImageOpsTile({
    required List<int> imageBytes,
    required int cols,
    required int rows,
  });

  Uint8List crateApiImageprocOpsTranslate({
    required List<int> imageBytes,
    required int tx,
    required int ty,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Uint8List crateApiImageprocOpsAdaptiveThreshold({
    required List<int> imageBytes,
    required int blockRadius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(blockRadius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsAdaptiveThresholdConstMeta,
        argValues: [imageBytes, blockRadius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsAdaptiveThresholdConstMeta =>
      const TaskConstMeta(
        debugName: "adaptive_threshold",
        argNames: ["imageBytes", "blockRadius"],
      );

  @override
  Uint8List crateApiImageOpsAdjustBrightness({
    required List<int> imageBytes,
    required int value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsAdjustBrightnessConstMeta,
        argValues: [imageBytes, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsAdjustBrightnessConstMeta =>
      const TaskConstMeta(
        debugName: "adjust_brightness",
        argNames: ["imageBytes", "value"],
      );

  @override
  Uint8List crateApiImageOpsAdjustContrast({
    required List<int> imageBytes,
    required double value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsAdjustContrastConstMeta,
        argValues: [imageBytes, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsAdjustContrastConstMeta =>
      const TaskConstMeta(
        debugName: "adjust_contrast",
        argNames: ["imageBytes", "value"],
      );

  @override
  Uint8List crateApiImageprocOpsBilateralFilter({
    required List<int> imageBytes,
    required int windowSize,
    required double sigmaColor,
    required double sigmaSpatial,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(windowSize, serializer);
          sse_encode_f_32(sigmaColor, serializer);
          sse_encode_f_32(sigmaSpatial, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsBilateralFilterConstMeta,
        argValues: [imageBytes, windowSize, sigmaColor, sigmaSpatial],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsBilateralFilterConstMeta =>
      const TaskConstMeta(
        debugName: "bilateral_filter",
        argNames: ["imageBytes", "windowSize", "sigmaColor", "sigmaSpatial"],
      );

  @override
  Uint8List crateApiImageOpsBlur({
    required List<int> imageBytes,
    required double sigma,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(sigma, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsBlurConstMeta,
        argValues: [imageBytes, sigma],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsBlurConstMeta =>
      const TaskConstMeta(debugName: "blur", argNames: ["imageBytes", "sigma"]);

  @override
  Uint8List crateApiImageprocOpsBoxFilter({
    required List<int> imageBytes,
    required int xRadius,
    required int yRadius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(xRadius, serializer);
          sse_encode_u_32(yRadius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsBoxFilterConstMeta,
        argValues: [imageBytes, xRadius, yRadius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsBoxFilterConstMeta =>
      const TaskConstMeta(
        debugName: "box_filter",
        argNames: ["imageBytes", "xRadius", "yRadius"],
      );

  @override
  Uint8List crateApiImageprocOpsCanny({
    required List<int> imageBytes,
    required double lowThreshold,
    required double highThreshold,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(lowThreshold, serializer);
          sse_encode_f_32(highThreshold, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsCannyConstMeta,
        argValues: [imageBytes, lowThreshold, highThreshold],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsCannyConstMeta => const TaskConstMeta(
    debugName: "canny",
    argNames: ["imageBytes", "lowThreshold", "highThreshold"],
  );

  @override
  Uint8List crateApiImageOpsConvertFormat({
    required List<int> imageBytes,
    required String targetFormat,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_String(targetFormat, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsConvertFormatConstMeta,
        argValues: [imageBytes, targetFormat],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsConvertFormatConstMeta =>
      const TaskConstMeta(
        debugName: "convert_format",
        argNames: ["imageBytes", "targetFormat"],
      );

  @override
  Uint8List crateApiImageOpsCreateBlank({
    required int width,
    required int height,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsCreateBlankConstMeta,
        argValues: [width, height, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsCreateBlankConstMeta =>
      const TaskConstMeta(
        debugName: "create_blank",
        argNames: ["width", "height", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageOpsCrop({
    required List<int> imageBytes,
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(x, serializer);
          sse_encode_u_32(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsCropConstMeta,
        argValues: [imageBytes, x, y, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsCropConstMeta => const TaskConstMeta(
    debugName: "crop",
    argNames: ["imageBytes", "x", "y", "width", "height"],
  );

  @override
  Uint8List crateApiImageprocOpsDilate({
    required List<int> imageBytes,
    required int radius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(radius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDilateConstMeta,
        argValues: [imageBytes, radius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDilateConstMeta => const TaskConstMeta(
    debugName: "dilate",
    argNames: ["imageBytes", "radius"],
  );

  @override
  Uint8List crateApiImageprocOpsDistanceTransform({
    required List<int> imageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDistanceTransformConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDistanceTransformConstMeta =>
      const TaskConstMeta(
        debugName: "distance_transform",
        argNames: ["imageBytes"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawAntialiasedLine({
    required List<int> imageBytes,
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(x1, serializer);
          sse_encode_i_32(y1, serializer);
          sse_encode_i_32(x2, serializer);
          sse_encode_i_32(y2, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawAntialiasedLineConstMeta,
        argValues: [imageBytes, x1, y1, x2, y2, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawAntialiasedLineConstMeta =>
      const TaskConstMeta(
        debugName: "draw_antialiased_line",
        argNames: ["imageBytes", "x1", "y1", "x2", "y2", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawCross({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(cx, serializer);
          sse_encode_i_32(cy, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawCrossConstMeta,
        argValues: [imageBytes, cx, cy, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawCrossConstMeta =>
      const TaskConstMeta(
        debugName: "draw_cross",
        argNames: ["imageBytes", "cx", "cy", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawCubicBezier({
    required List<int> imageBytes,
    required double startX,
    required double startY,
    required double endX,
    required double endY,
    required double ctrl1X,
    required double ctrl1Y,
    required double ctrl2X,
    required double ctrl2Y,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(startX, serializer);
          sse_encode_f_32(startY, serializer);
          sse_encode_f_32(endX, serializer);
          sse_encode_f_32(endY, serializer);
          sse_encode_f_32(ctrl1X, serializer);
          sse_encode_f_32(ctrl1Y, serializer);
          sse_encode_f_32(ctrl2X, serializer);
          sse_encode_f_32(ctrl2Y, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawCubicBezierConstMeta,
        argValues: [
          imageBytes,
          startX,
          startY,
          endX,
          endY,
          ctrl1X,
          ctrl1Y,
          ctrl2X,
          ctrl2Y,
          r,
          g,
          b,
          a,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawCubicBezierConstMeta =>
      const TaskConstMeta(
        debugName: "draw_cubic_bezier",
        argNames: [
          "imageBytes",
          "startX",
          "startY",
          "endX",
          "endY",
          "ctrl1X",
          "ctrl1Y",
          "ctrl2X",
          "ctrl2Y",
          "r",
          "g",
          "b",
          "a",
        ],
      );

  @override
  Uint8List crateApiImageprocOpsDrawFilledCircle({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int radius,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(cx, serializer);
          sse_encode_i_32(cy, serializer);
          sse_encode_i_32(radius, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawFilledCircleConstMeta,
        argValues: [imageBytes, cx, cy, radius, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawFilledCircleConstMeta =>
      const TaskConstMeta(
        debugName: "draw_filled_circle",
        argNames: ["imageBytes", "cx", "cy", "radius", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawFilledEllipse({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int widthRadius,
    required int heightRadius,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(cx, serializer);
          sse_encode_i_32(cy, serializer);
          sse_encode_i_32(widthRadius, serializer);
          sse_encode_i_32(heightRadius, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawFilledEllipseConstMeta,
        argValues: [imageBytes, cx, cy, widthRadius, heightRadius, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawFilledEllipseConstMeta =>
      const TaskConstMeta(
        debugName: "draw_filled_ellipse",
        argNames: [
          "imageBytes",
          "cx",
          "cy",
          "widthRadius",
          "heightRadius",
          "r",
          "g",
          "b",
          "a",
        ],
      );

  @override
  Uint8List crateApiImageprocOpsDrawFilledPolygon({
    required List<int> imageBytes,
    required List<LumePoint> points,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_list_lume_point(points, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawFilledPolygonConstMeta,
        argValues: [imageBytes, points, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawFilledPolygonConstMeta =>
      const TaskConstMeta(
        debugName: "draw_filled_polygon",
        argNames: ["imageBytes", "points", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawFilledRect({
    required List<int> imageBytes,
    required int x,
    required int y,
    required int width,
    required int height,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawFilledRectConstMeta,
        argValues: [imageBytes, x, y, width, height, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawFilledRectConstMeta =>
      const TaskConstMeta(
        debugName: "draw_filled_rect",
        argNames: [
          "imageBytes",
          "x",
          "y",
          "width",
          "height",
          "r",
          "g",
          "b",
          "a",
        ],
      );

  @override
  Uint8List crateApiImageprocOpsDrawHollowCircle({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int radius,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(cx, serializer);
          sse_encode_i_32(cy, serializer);
          sse_encode_i_32(radius, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawHollowCircleConstMeta,
        argValues: [imageBytes, cx, cy, radius, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawHollowCircleConstMeta =>
      const TaskConstMeta(
        debugName: "draw_hollow_circle",
        argNames: ["imageBytes", "cx", "cy", "radius", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawHollowEllipse({
    required List<int> imageBytes,
    required int cx,
    required int cy,
    required int widthRadius,
    required int heightRadius,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(cx, serializer);
          sse_encode_i_32(cy, serializer);
          sse_encode_i_32(widthRadius, serializer);
          sse_encode_i_32(heightRadius, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawHollowEllipseConstMeta,
        argValues: [imageBytes, cx, cy, widthRadius, heightRadius, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawHollowEllipseConstMeta =>
      const TaskConstMeta(
        debugName: "draw_hollow_ellipse",
        argNames: [
          "imageBytes",
          "cx",
          "cy",
          "widthRadius",
          "heightRadius",
          "r",
          "g",
          "b",
          "a",
        ],
      );

  @override
  Uint8List crateApiImageprocOpsDrawHollowPolygon({
    required List<int> imageBytes,
    required List<LumePoint> points,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_list_lume_point(points, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawHollowPolygonConstMeta,
        argValues: [imageBytes, points, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawHollowPolygonConstMeta =>
      const TaskConstMeta(
        debugName: "draw_hollow_polygon",
        argNames: ["imageBytes", "points", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsDrawHollowRect({
    required List<int> imageBytes,
    required int x,
    required int y,
    required int width,
    required int height,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawHollowRectConstMeta,
        argValues: [imageBytes, x, y, width, height, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawHollowRectConstMeta =>
      const TaskConstMeta(
        debugName: "draw_hollow_rect",
        argNames: [
          "imageBytes",
          "x",
          "y",
          "width",
          "height",
          "r",
          "g",
          "b",
          "a",
        ],
      );

  @override
  Uint8List crateApiImageprocOpsDrawLine({
    required List<int> imageBytes,
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    required int r,
    required int g,
    required int b,
    required int a,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(x1, serializer);
          sse_encode_i_32(y1, serializer);
          sse_encode_i_32(x2, serializer);
          sse_encode_i_32(y2, serializer);
          sse_encode_u_8(r, serializer);
          sse_encode_u_8(g, serializer);
          sse_encode_u_8(b, serializer);
          sse_encode_u_8(a, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsDrawLineConstMeta,
        argValues: [imageBytes, x1, y1, x2, y2, r, g, b, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsDrawLineConstMeta =>
      const TaskConstMeta(
        debugName: "draw_line",
        argNames: ["imageBytes", "x1", "y1", "x2", "y2", "r", "g", "b", "a"],
      );

  @override
  Uint8List crateApiImageprocOpsEqualizeHistogram({
    required List<int> imageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsEqualizeHistogramConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsEqualizeHistogramConstMeta =>
      const TaskConstMeta(
        debugName: "equalize_histogram",
        argNames: ["imageBytes"],
      );

  @override
  Uint8List crateApiImageprocOpsErode({
    required List<int> imageBytes,
    required int radius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(radius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsErodeConstMeta,
        argValues: [imageBytes, radius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsErodeConstMeta => const TaskConstMeta(
    debugName: "erode",
    argNames: ["imageBytes", "radius"],
  );

  @override
  Uint8List crateApiImageOpsExtractChannel({
    required List<int> imageBytes,
    required int channel,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(channel, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsExtractChannelConstMeta,
        argValues: [imageBytes, channel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsExtractChannelConstMeta =>
      const TaskConstMeta(
        debugName: "extract_channel",
        argNames: ["imageBytes", "channel"],
      );

  @override
  List<LumeContour> crateApiImageprocOpsFindContours({
    required List<int> imageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lume_contour,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsFindContoursConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsFindContoursConstMeta =>
      const TaskConstMeta(debugName: "find_contours", argNames: ["imageBytes"]);

  @override
  Uint8List crateApiImageOpsFlipHorizontal({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsFlipHorizontalConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsFlipHorizontalConstMeta =>
      const TaskConstMeta(
        debugName: "flip_horizontal",
        argNames: ["imageBytes"],
      );

  @override
  Uint8List crateApiImageOpsFlipVertical({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsFlipVerticalConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsFlipVerticalConstMeta =>
      const TaskConstMeta(debugName: "flip_vertical", argNames: ["imageBytes"]);

  @override
  Uint8List crateApiImageprocOpsGaussianBlur({
    required List<int> imageBytes,
    required double sigma,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(sigma, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsGaussianBlurConstMeta,
        argValues: [imageBytes, sigma],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsGaussianBlurConstMeta =>
      const TaskConstMeta(
        debugName: "gaussian_blur",
        argNames: ["imageBytes", "sigma"],
      );

  @override
  Uint8List crateApiImageprocOpsGaussianNoise({
    required List<int> imageBytes,
    required double mean,
    required double stddev,
    required BigInt seed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_64(mean, serializer);
          sse_encode_f_64(stddev, serializer);
          sse_encode_u_64(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsGaussianNoiseConstMeta,
        argValues: [imageBytes, mean, stddev, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsGaussianNoiseConstMeta =>
      const TaskConstMeta(
        debugName: "gaussian_noise",
        argNames: ["imageBytes", "mean", "stddev", "seed"],
      );

  @override
  LumeImageInfo crateApiImageOpsGetImageInfo({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lume_image_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsGetImageInfoConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsGetImageInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_image_info",
        argNames: ["imageBytes"],
      );

  @override
  LumeColor crateApiImageOpsGetPixel({
    required List<int> imageBytes,
    required int x,
    required int y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(x, serializer);
          sse_encode_u_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lume_color,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsGetPixelConstMeta,
        argValues: [imageBytes, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsGetPixelConstMeta => const TaskConstMeta(
    debugName: "get_pixel",
    argNames: ["imageBytes", "x", "y"],
  );

  @override
  Uint8List crateApiImageOpsGrayscale({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsGrayscaleConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsGrayscaleConstMeta =>
      const TaskConstMeta(debugName: "grayscale", argNames: ["imageBytes"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Uint8List crateApiImageOpsHuerotate({
    required List<int> imageBytes,
    required int degrees,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(degrees, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsHuerotateConstMeta,
        argValues: [imageBytes, degrees],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsHuerotateConstMeta => const TaskConstMeta(
    debugName: "huerotate",
    argNames: ["imageBytes", "degrees"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Uint8List crateApiImageOpsInvertColors({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsInvertColorsConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsInvertColorsConstMeta =>
      const TaskConstMeta(debugName: "invert_colors", argNames: ["imageBytes"]);

  @override
  Uint8List crateApiImageprocOpsLaplacianFilter({
    required List<int> imageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsLaplacianFilterConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsLaplacianFilterConstMeta =>
      const TaskConstMeta(
        debugName: "laplacian_filter",
        argNames: ["imageBytes"],
      );

  @override
  Uint8List crateApiImageprocOpsMedianFilter({
    required List<int> imageBytes,
    required int xRadius,
    required int yRadius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(xRadius, serializer);
          sse_encode_u_32(yRadius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsMedianFilterConstMeta,
        argValues: [imageBytes, xRadius, yRadius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsMedianFilterConstMeta =>
      const TaskConstMeta(
        debugName: "median_filter",
        argNames: ["imageBytes", "xRadius", "yRadius"],
      );

  @override
  Uint8List crateApiImageprocOpsMorphologicalClose({
    required List<int> imageBytes,
    required int radius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(radius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsMorphologicalCloseConstMeta,
        argValues: [imageBytes, radius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsMorphologicalCloseConstMeta =>
      const TaskConstMeta(
        debugName: "morphological_close",
        argNames: ["imageBytes", "radius"],
      );

  @override
  Uint8List crateApiImageprocOpsMorphologicalOpen({
    required List<int> imageBytes,
    required int radius,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(radius, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsMorphologicalOpenConstMeta,
        argValues: [imageBytes, radius],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsMorphologicalOpenConstMeta =>
      const TaskConstMeta(
        debugName: "morphological_open",
        argNames: ["imageBytes", "radius"],
      );

  @override
  Uint8List crateApiImageprocOpsOtsuThreshold({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsOtsuThresholdConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsOtsuThresholdConstMeta =>
      const TaskConstMeta(
        debugName: "otsu_threshold",
        argNames: ["imageBytes"],
      );

  @override
  Uint8List crateApiImageOpsOverlay({
    required List<int> baseBytes,
    required List<int> overlayBytes,
    required PlatformInt64 x,
    required PlatformInt64 y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(baseBytes, serializer);
          sse_encode_list_prim_u_8_loose(overlayBytes, serializer);
          sse_encode_i_64(x, serializer);
          sse_encode_i_64(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsOverlayConstMeta,
        argValues: [baseBytes, overlayBytes, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsOverlayConstMeta => const TaskConstMeta(
    debugName: "overlay",
    argNames: ["baseBytes", "overlayBytes", "x", "y"],
  );

  @override
  Uint8List crateApiImageOpsResize({
    required List<int> imageBytes,
    required int width,
    required int height,
    required bool keepAspectRatio,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_bool(keepAspectRatio, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsResizeConstMeta,
        argValues: [imageBytes, width, height, keepAspectRatio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsResizeConstMeta => const TaskConstMeta(
    debugName: "resize",
    argNames: ["imageBytes", "width", "height", "keepAspectRatio"],
  );

  @override
  Uint8List crateApiImageOpsResizeWithFilter({
    required List<int> imageBytes,
    required int width,
    required int height,
    required String filter,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_String(filter, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsResizeWithFilterConstMeta,
        argValues: [imageBytes, width, height, filter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsResizeWithFilterConstMeta =>
      const TaskConstMeta(
        debugName: "resize_with_filter",
        argNames: ["imageBytes", "width", "height", "filter"],
      );

  @override
  Uint8List crateApiImageOpsRotate({
    required List<int> imageBytes,
    required int degrees,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(degrees, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsRotateConstMeta,
        argValues: [imageBytes, degrees],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsRotateConstMeta => const TaskConstMeta(
    debugName: "rotate",
    argNames: ["imageBytes", "degrees"],
  );

  @override
  Uint8List crateApiImageprocOpsRotateAboutCenter({
    required List<int> imageBytes,
    required double theta,
    required int bgR,
    required int bgG,
    required int bgB,
    required int bgA,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(theta, serializer);
          sse_encode_u_8(bgR, serializer);
          sse_encode_u_8(bgG, serializer);
          sse_encode_u_8(bgB, serializer);
          sse_encode_u_8(bgA, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsRotateAboutCenterConstMeta,
        argValues: [imageBytes, theta, bgR, bgG, bgB, bgA],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsRotateAboutCenterConstMeta =>
      const TaskConstMeta(
        debugName: "rotate_about_center",
        argNames: ["imageBytes", "theta", "bgR", "bgG", "bgB", "bgA"],
      );

  @override
  Uint8List crateApiImageprocOpsSaltAndPepperNoise({
    required List<int> imageBytes,
    required double rate,
    required BigInt seed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_64(rate, serializer);
          sse_encode_u_64(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 50)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsSaltAndPepperNoiseConstMeta,
        argValues: [imageBytes, rate, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsSaltAndPepperNoiseConstMeta =>
      const TaskConstMeta(
        debugName: "salt_and_pepper_noise",
        argNames: ["imageBytes", "rate", "seed"],
      );

  @override
  Uint8List crateApiImageprocOpsSeamCarveWidth({
    required List<int> imageBytes,
    required int newWidth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(newWidth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 51)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsSeamCarveWidthConstMeta,
        argValues: [imageBytes, newWidth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsSeamCarveWidthConstMeta =>
      const TaskConstMeta(
        debugName: "seam_carve_width",
        argNames: ["imageBytes", "newWidth"],
      );

  @override
  Uint8List crateApiImageOpsSharpen({
    required List<int> imageBytes,
    required double sigma,
    required int threshold,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(sigma, serializer);
          sse_encode_i_32(threshold, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 52)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsSharpenConstMeta,
        argValues: [imageBytes, sigma, threshold],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsSharpenConstMeta => const TaskConstMeta(
    debugName: "sharpen",
    argNames: ["imageBytes", "sigma", "threshold"],
  );

  @override
  Uint8List crateApiImageprocOpsSharpen3X3({required List<int> imageBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 53)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsSharpen3X3ConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsSharpen3X3ConstMeta =>
      const TaskConstMeta(debugName: "sharpen3x3", argNames: ["imageBytes"]);

  @override
  Uint8List crateApiImageprocOpsSharpenGaussian({
    required List<int> imageBytes,
    required double sigma,
    required double amount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_f_32(sigma, serializer);
          sse_encode_f_32(amount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 54)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsSharpenGaussianConstMeta,
        argValues: [imageBytes, sigma, amount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsSharpenGaussianConstMeta =>
      const TaskConstMeta(
        debugName: "sharpen_gaussian",
        argNames: ["imageBytes", "sigma", "amount"],
      );

  @override
  Uint8List crateApiImageprocOpsSobelGradients({
    required List<int> imageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 55)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsSobelGradientsConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsSobelGradientsConstMeta =>
      const TaskConstMeta(
        debugName: "sobel_gradients",
        argNames: ["imageBytes"],
      );

  @override
  Uint8List crateApiImageprocOpsStretchContrast({
    required List<int> imageBytes,
    required int inputLower,
    required int inputUpper,
    required int outputLower,
    required int outputUpper,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(inputLower, serializer);
          sse_encode_u_8(inputUpper, serializer);
          sse_encode_u_8(outputLower, serializer);
          sse_encode_u_8(outputUpper, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 56)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsStretchContrastConstMeta,
        argValues: [
          imageBytes,
          inputLower,
          inputUpper,
          outputLower,
          outputUpper,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsStretchContrastConstMeta =>
      const TaskConstMeta(
        debugName: "stretch_contrast",
        argNames: [
          "imageBytes",
          "inputLower",
          "inputUpper",
          "outputLower",
          "outputUpper",
        ],
      );

  @override
  Uint8List crateApiImageprocOpsThreshold({
    required List<int> imageBytes,
    required int value,
    required bool invert,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_8(value, serializer);
          sse_encode_bool(invert, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 57)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsThresholdConstMeta,
        argValues: [imageBytes, value, invert],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsThresholdConstMeta =>
      const TaskConstMeta(
        debugName: "threshold",
        argNames: ["imageBytes", "value", "invert"],
      );

  @override
  Uint8List crateApiImageOpsThumbnail({
    required List<int> imageBytes,
    required int maxWidth,
    required int maxHeight,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(maxWidth, serializer);
          sse_encode_u_32(maxHeight, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 58)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsThumbnailConstMeta,
        argValues: [imageBytes, maxWidth, maxHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsThumbnailConstMeta => const TaskConstMeta(
    debugName: "thumbnail",
    argNames: ["imageBytes", "maxWidth", "maxHeight"],
  );

  @override
  Uint8List crateApiImageOpsThumbnailExact({
    required List<int> imageBytes,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 59)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsThumbnailExactConstMeta,
        argValues: [imageBytes, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsThumbnailExactConstMeta =>
      const TaskConstMeta(
        debugName: "thumbnail_exact",
        argNames: ["imageBytes", "width", "height"],
      );

  @override
  Uint8List crateApiImageOpsTile({
    required List<int> imageBytes,
    required int cols,
    required int rows,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 60)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageOpsTileConstMeta,
        argValues: [imageBytes, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageOpsTileConstMeta => const TaskConstMeta(
    debugName: "tile",
    argNames: ["imageBytes", "cols", "rows"],
  );

  @override
  Uint8List crateApiImageprocOpsTranslate({
    required List<int> imageBytes,
    required int tx,
    required int ty,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_i_32(tx, serializer);
          sse_encode_i_32(ty, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 61)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImageprocOpsTranslateConstMeta,
        argValues: [imageBytes, tx, ty],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageprocOpsTranslateConstMeta =>
      const TaskConstMeta(
        debugName: "translate",
        argNames: ["imageBytes", "tx", "ty"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<LumeContour> dco_decode_list_lume_contour(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lume_contour).toList();
  }

  @protected
  List<LumePoint> dco_decode_list_lume_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lume_point).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LumeColor dco_decode_lume_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LumeColor(
      r: dco_decode_u_8(arr[0]),
      g: dco_decode_u_8(arr[1]),
      b: dco_decode_u_8(arr[2]),
      a: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  LumeContour dco_decode_lume_contour(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LumeContour(
      points: dco_decode_list_lume_point(arr[0]),
      borderType: dco_decode_String(arr[1]),
      parent: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  LumeImageInfo dco_decode_lume_image_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LumeImageInfo(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      format: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  LumePoint dco_decode_lume_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LumePoint(x: dco_decode_i_32(arr[0]), y: dco_decode_i_32(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<LumeContour> sse_decode_list_lume_contour(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LumeContour>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lume_contour(deserializer));
    }
    return ans_;
  }

  @protected
  List<LumePoint> sse_decode_list_lume_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LumePoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lume_point(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LumeColor sse_decode_lume_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_r = sse_decode_u_8(deserializer);
    var var_g = sse_decode_u_8(deserializer);
    var var_b = sse_decode_u_8(deserializer);
    var var_a = sse_decode_u_8(deserializer);
    return LumeColor(r: var_r, g: var_g, b: var_b, a: var_a);
  }

  @protected
  LumeContour sse_decode_lume_contour(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_points = sse_decode_list_lume_point(deserializer);
    var var_borderType = sse_decode_String(deserializer);
    var var_parent = sse_decode_i_32(deserializer);
    return LumeContour(
      points: var_points,
      borderType: var_borderType,
      parent: var_parent,
    );
  }

  @protected
  LumeImageInfo sse_decode_lume_image_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_32(deserializer);
    return LumeImageInfo(
      width: var_width,
      height: var_height,
      format: var_format,
      sizeBytes: var_sizeBytes,
    );
  }

  @protected
  LumePoint sse_decode_lume_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_i_32(deserializer);
    var var_y = sse_decode_i_32(deserializer);
    return LumePoint(x: var_x, y: var_y);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_lume_contour(
    List<LumeContour> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lume_contour(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lume_point(
    List<LumePoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lume_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_lume_color(LumeColor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.r, serializer);
    sse_encode_u_8(self.g, serializer);
    sse_encode_u_8(self.b, serializer);
    sse_encode_u_8(self.a, serializer);
  }

  @protected
  void sse_encode_lume_contour(LumeContour self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_lume_point(self.points, serializer);
    sse_encode_String(self.borderType, serializer);
    sse_encode_i_32(self.parent, serializer);
  }

  @protected
  void sse_encode_lume_image_info(
    LumeImageInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_u_32(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_lume_point(LumePoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.x, serializer);
    sse_encode_i_32(self.y, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
